services:
  mysql:
    image: mysql:8.0
    container_name: petclinic-mysql
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: HA705010
    ports:
      - "3306:3306"
    networks:
      - petclinic-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pHA705010"]
      interval: 10s
      timeout: 5s
      retries: 5
    


  app:
    image: petclinic-app:latest
    container_name: petclinic-app
    ports:
      - "9123:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - petclinic-network

networks:
  petclinic-network:
    external: true
    driver: bridge


