services:
  mysql:
    image: mysql:8.0
    container_name: petclinic-mysql
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: root
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: Ha705010
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: petclinic-app:latest
    container_name: petclinic-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9123:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
